stages:
  - test
  
KKconverter-test_on_test:
  stage: test
  image: nexus.vsk.ru:8182/vsk/maven:3.6.1-jdk11
  script:
    - echo "KKconverter tests on Test with maven..."
    - pwd
    - ls -l src/test/java/kkconverter/products/
    - mvn test -Dtest=UnitTests -Darg=test
  when: manual
  tags:
    - docker
